### PR TITLE
Components-Drop-API.md

### PR DESCRIPTION
**Pull request by NanNor**
deleted the public void in line 13 and 14

### CODE REVIEW

**Comment by cburkert** [comment]
You can remove the whole *-API.md files. Have a look if the javadoc in the core repo is sufficient for these send and receive methods, if not, file an issue.

**Comment by jasinai** [comment]
And remove also the lines 13 and 15 in https://github.com/Qabel/qabel.github.io/blob/master/_data/docs.yml, please.

**Comment by cburkert** [comment]
The storage API is IMHO sufficiently documented. I haven't checked to drop API, yet.

**Comment by NanNor** [comment]
I checked drop API. Looked good for me. Except for DropDeserializer there is no documentation at all. I'm not sure if this class needs a doc.

**Comment by thechauffeur** [comment]
@cburkert please merge, explain or close this. Since here are a few issues and pull requests involved (in different repositories) I don't know what is the plan exactly :)

**Comment by cburkert** [comment]
Replaced by #93

**Pull request closed without merging**
