### PR TITLE
Proof of work Spec

### LINKED ISSUE #68: Qabel proof-of-work page
This [page](http://qabel.github.io/docs/Qabel-Protocol-ProofOfWork/) is a draft. For an implementation research must be done and a specification is needed.

### PR DESCRIPTION
**Pull request by roeslpa**
Wrote a more specific description of the proof of work. Resolves #68

### CODE REVIEW

**Comment by cburkert** [comment]
@roeslpa Your suggestion looks plausible to me. However, I know too little about proof-of-work protocols to do a in-depth analysis.
For now, this should do, but we should keep this in mind for later auditing.
Furthermore, I'd would be useful to read what inspired your suggestion (existing protocols).

**Comment by audax** [comment]
@cburkert : was that an "ack"?

**Comment by roeslpa** [comment]
@cburkert I added my inspiration and modified the protocol to prevent precomputation. Would you ack for now and we keep it in mind for an audit?

**Comment by thechauffeur** [comment]
I have several question about this spec until I can ack it. We should discuss this in real-time and post the outcome here.

In any case we need an issue (enhancement, future work) about independently auditing the proof-of-work spec.

**Comment by thechauffeur** [comment]
My questions are answered and this spec looks sane to increase the amount of work someone must do to (D)DoS the (drop) system.

We could force this protocol only on `suspicious` connections (e.g. on connections using IPs with more than `r` requests per time unit).

**Pull request merged**
