### PR TITLE
Delete language specific API documentation

### PR DESCRIPTION
**Pull request by NanNor**
-

### CODE REVIEW

**Comment by thechauffeur** [comment]
@NanNor please add a description to the pull request describing the purpose of this request (i.e. explaining or even justifying it).

If this PR has something to do with an issue or even another PR you can reference a PR or issue with writing `#37`. If this PR is intended to close an issue you can write `Closes #37`. Using this syntax GitHub will automatically close an issue after this PR is merged.

**Comment by NanNor** [comment]
this pull request is about issue #83 . the Drop and storage doc is more detailed in javadoc

**Comment by thechauffeur** [comment]
@cburkert please merge, explain or close this. Since here are a few issues and pull requests involved (in different repositories) I don't know what is the plan exactly :)

**Comment by cburkert** [comment]
@NanNor don't forget to update the table of contents as @jasinai noted in https://github.com/Qabel/qabel.github.io/pull/92#issuecomment-120388654

**Comment by NanNor** [comment]
merged pull request #93 and #94 into this pull request

**Comment by cburkert** [comment]
> @NanNor don't forget to update the table of contents as @jasinai noted in #92 (comment)

Already happened in #95 

Thus this is done. Closes #83

**Pull request merged**
